package com.mounacheikhna.screenshots

import com.android.build.gradle.AppPlugin
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.Task
import org.gradle.api.tasks.Exec
import org.gradle.api.tasks.StopExecutionException

/**
 * Created by m.cheikhna on 31/12/2015.
 */
class ScreenshotsPlugin implements Plugin<Project> {

  private static final String TASK_PREFIX = "screenshots"
  private static final String GROUP_SCREENSHOTS = "screenshots"

  @Override
  void apply(Project project) {
    println "apply plugin"
    if (!hasPlugin(project, AppPlugin)) {
      throw new StopExecutionException("The 'com.android.application' plugin is required.")
    }
    project.extensions.add("screenshots", ScreenshotsExtension)

    Task allScreenshotsTask = project.tasks.create("all$TASK_PREFIX")
    allScreenshotsTask.group = GROUP_SCREENSHOTS
    allScreenshotsTask.description =
        '''Takes screenshots generated by spoon on all the connected devices for variation,
            copies them into play folder each in the right place.'''

    project.afterEvaluate {
      println "afterEvaluate"
      Task imageMagicAll = createImageMagicAllTask(project)
      //TODO: we should change the local of the device -> how about starting it ourself

      List<String> locales = project.screenshots.locales

      String productFlavor = project.screenshots.productFlavor
      def flavorTaskName = productFlavor.capitalize()
      allScreenshotsTask.dependsOn project.tasks.findByName("assemble$flavorTaskName")
      allScreenshotsTask.dependsOn project.tasks.findByName("assembleAndroidTest")

      locales.each {
        println "For locale $it" //maybe the pb is that this cleans the folder ? -> Yes it does
        Task spoonLocalTask = createSpoonRunTaskByLocale(project, it)

        Task localScreenshotsTask = project.tasks.create("$it$TASK_PREFIX", ProcessSpoonOutputTask)
        // i need to pass param local to this
        imageMagicAll.dependsOn spoonLocalTask
        localScreenshotsTask.dependsOn imageMagicAll

        println " Before allScreenshotsTask.dependsOn localScreenshotsTask "
        allScreenshotsTask.dependsOn localScreenshotsTask
      }
    }
  }

  private Task createSpoonRunTaskByLocale(Project project, String locale) {
    println "createSpoonRunTaskByLocale"

    String productFlavor = project.screenshots.productFlavor
    String prefixApk = "${project.buildDir}/outputs/apk/app-$productFlavor-${project.screenshots.buildType}"
    String apkPath = "$prefixApk-unaligned.apk"
    //TODO: maybe replace -unaligned part with regex match like **
    String testApkPath = "$prefixApk-androidTest-unaligned.apk"
    String spoonRunnerLibPath = "${project.rootDir}/" +
        "" + "screenshots-plugin/lib/spoon-runner-1.3.1-jar-with-d" + "ependencies.jar"
    Task task = project.tasks.create("${locale}spoonRunTask", Exec) {
      commandLine "java", "-jar", "$spoonRunnerLibPath",
          "--apk", "$apkPath", "--test-apk", "$testApkPath",
          "--class-name", "com.mounacheikhna.screenshots.ScreenshotsTest",
          "--e", "locale=$locale"
    }
    task
  }

  private Task createImageMagicAllTask(Project project) {
    println "createImageMagicAllTask"

    String buildDestDir = project.screenshots.buildDestDir ?: project.buildDir
    String imagesParentFolder = "$buildDestDir/${project.screenshots.buildType}/image/"
    println " imagesParentFolder : $imagesParentFolder"

    String frameFileName = "${project.projectDir}/frames/galaxy_nexus_port_back.png";
    String deviceFrameRequiredSize = "1270x1290"
    String labelTextSize = "40"
    String topOffset = "40"
    String screenshotsTitle = "Title for this screenshot"

    Task imageMagicAll = project.tasks.create("imageMagicAll")

    //TODO: some parameters should be provided by user such as background color, text label, frame file path
    new File(imagesParentFolder).listFiles({ it.isDirectory() } as FileFilter)
        .each {
      dir ->
        dir.eachFileMatch(~/.*\.png/) {
          println "eachFileMatch for ${it.name}"

          String imageFileName = it.name
          String imTaskName = "im${dir.name}${imageFileName.replace(".png", "").replace("_", "")}Task"
          Task imTask = project.tasks.create(imTaskName)
          def taskSuffixName = "${dir.name}$imageFileName"
          Task resizeTask = project.tasks.create("c1$taskSuffixName", Exec) {
            println "resizeTask"
            workingDir dir
            commandLine "convert", "$imageFileName", "-resize", deviceFrameRequiredSize,
                "$imageFileName"
          }

          Task composeTask = project.tasks.create("c2$taskSuffixName", Exec) {
            println "composeTask"
            workingDir dir
            commandLine "convert", "$frameFileName", "$imageFileName",
                "-gravity", "center", "-compose", "over", "-composite",
                "-fill", "gold", "-channel", "RGBA", "-opaque", "none", "$imageFileName"
          }

          Task backgroundLabelTask = project.tasks.create("c3$taskSuffixName", Exec) {
            println "backgroundLabelTask"
            workingDir dir
            commandLine "convert", "$imageFileName", "-background", "Gold", "-gravity",
                "North",
                "-pointsize", "$labelTextSize", "-density", "100", "-fill", "white",
                "-annotate", "+0+$topOffset", "$screenshotsTitle",
                "$imageFileName"
          }
          imTask.dependsOn resizeTask
          imTask.dependsOn composeTask
          imTask.dependsOn backgroundLabelTask
          imageMagicAll.dependsOn imTask
        }
    }
    imageMagicAll.group = GROUP_SCREENSHOTS
    imageMagicAll
  }

  static def hasPlugin(Project project, Class<? extends Plugin> plugin) {
    return project.plugins.hasPlugin(plugin)
  }
}
